apiVersion: v1
kind: Service
metadata:
  name: mvnwebapp-service
spec:
  selector:
    app: mvnwebapp
  type: NodePort
  ports:
  - name: mvnwebapp
    protocol: TCP
    port: 6000
    targetPort: 8080